[project]
name = "wetting-transition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "polars>=1.22.0",
    "scipy>=1.13.1",
]
